#%RAML 1.0
title: Quản lý Thư viện API
version: v1
baseUri: http://api.library.com/api
mediaType: application/json

types:
  Book:
    type: object
    properties:
      id?: string
      title: string
      author: string

/books:
  get:
    description: Lấy danh sách sách
    responses:
      200:
        body:
          type: Book[]
  post:
    description: Thêm sách mới
    body:
      type: Book
    responses:
      201:
        body:
          type: Book
